In [5]:
import pandas as pd

# Load the JSON files
card_details = pd.read_json('products_singles_6(2).json')
price_data = pd.read_json('price_guide_6(3).json')

In [6]:
print(card_details.columns)
print(price_data.columns)

Index(['version', 'createdAt', 'products'], dtype='object')
Index(['version', 'createdAt', 'priceGuides'], dtype='object')

In [11]:

# Extract the nested data
card_details_flat = pd.json_normalize(card_details['products'])
price_data_flat = pd.json_normalize(price_data['priceGuides'])

# Display the extracted data to verify
card_details_flat.head()

,idProduct,name,idCategory,categoryName,idExpansion,idMetacard,dateAdded
0,273532,Weedle [Multiply],51,Pokémon Single,1585,340471,0000-00-00 00:00:00
1,273533,Kakuna [Bug Bite | Primal Clash],51,Pokémon Single,1585,340472,0000-00-00 00:00:00
2,273534,Beedrill [Allergic Shock | Twineedle],51,Pokémon Single,1585,340473,0000-00-00 00:00:00
3,273535,Tangela [Absorb | Vine Whip],51,Pokémon Single,1585,340146,0000-00-00 00:00:00
4,273536,Tangrowth [Mega Drain | Grass Knot],51,Pokémon Single,1585,340519,0000-00-00 00:00:00

In [10]:
price_data_flat.head()

,idProduct,idCategory,avg,low,trend,avg1,avg7,avg30,avg-holo,low-holo,trend-holo,avg1-holo,avg7-holo,avg30-holo
0,271439,52,64.00,37.97,83.40,NaN,NaN,NaN,NaN,NaN,3.93,NaN,NaN,NaN
1,271440,53,2800.00,19000.00,2127.88,NaN,NaN,NaN,NaN,NaN,178.28,NaN,NaN,NaN
2,271823,52,317.46,160.00,340.03,NaN,NaN,NaN,NaN,NaN,90.03,NaN,NaN,NaN
3,271824,53,9000.00,9500.00,7543.91,NaN,NaN,NaN,NaN,NaN,1782.45,NaN,NaN,NaN
4,271825,52,43.87,33.90,57.29,NaN,NaN,NaN,NaN,NaN,5.92,NaN,NaN,NaN

In [9]:
# Merge on 'idProduct'
merged_data = pd.merge(card_details_flat, price_data_flat, on='idProduct', how='inner')

# Display the merged data
merged_data.head()

,idProduct,name,idCategory_x,categoryName,idExpansion,idMetacard,dateAdded,idCategory_y,avg,low,trend,avg1,avg7,avg30,avg-holo,low-holo,trend-holo,avg1-holo,avg7-holo,avg30-holo
0,273532,Weedle [Multiply],51,Pokémon Single,1585,340471,0000-00-00 00:00:00,51,0.08,0.02,0.10,0.07,0.08,0.10,0.28,0.14,0.39,0.20,0.31,0.49
1,273533,Kakuna [Bug Bite | Primal Clash],51,Pokémon Single,1585,340472,0000-00-00 00:00:00,51,0.09,0.02,0.10,0.15,0.09,0.12,0.40,0.05,0.46,0.30,0.41,0.39
2,273534,Beedrill [Allergic Shock | Twineedle],51,Pokémon Single,1585,340473,0000-00-00 00:00:00,51,0.37,0.05,0.57,0.29,0.41,0.47,1.40,0.05,1.79,1.40,1.62,1.23
3,273535,Tangela [Absorb | Vine Whip],51,Pokémon Single,1585,340146,0000-00-00 00:00:00,51,0.09,0.02,0.07,0.10,0.07,0.11,0.18,0.08,0.53,0.20,0.27,0.48
4,273536,Tangrowth [Mega Drain | Grass Knot],51,Pokémon Single,1585,340519,0000-00-00 00:00:00,51,0.26,0.05,0.34,0.19,0.36,0.36,1.25,0.25,0.96,1.99,1.12,0.77

In [15]:
import requests
from bs4 import BeautifulSoup

# Define the base URL for the page you want to scrape
url = "https://www.cardmarket.com/"  # Adjust for Pokémon or other categories

# Headers to mimic a real browser request
headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0 Safari/537.36"
}

# Send a GET request
response = requests.get(url, headers=headers)
response_text = response.text
print(response_text)
# Check the response status
if response.status_code == 200:
    print("Request successful!")
    soup = BeautifulSoup(response.content, "html.parser")
else:
    print(f"Failed to fetch the page. Status code: {response.status_code}")

<!DOCTYPE html><html lang="en-US"><head><title>Just a moment...</title><meta http-equiv="Content-Type" content="text/html; charset=UTF-8"><meta http-equiv="X-UA-Compatible" content="IE=Edge"><meta name="robots" content="noindex,nofollow"><meta name="viewport" content="width=device-width,initial-scale=1"><style>*{box-sizing:border-box;margin:0;padding:0}html{line-height:1.15;-webkit-text-size-adjust:100%;color:#313131;font-family:system-ui,-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,Helvetica Neue,Arial,Noto Sans,sans-serif,Apple Color Emoji,Segoe UI Emoji,Segoe UI Symbol,Noto Color Emoji}body{display:flex;flex-direction:column;height:100vh;min-height:100vh}.main-content{margin:8rem auto;max-width:60rem;padding-left:1.5rem}@media (width <= 720px){.main-content{margin-top:4rem}}.h2{font-size:1.5rem;font-weight:500;line-height:2.25rem}@media (width <= 720px){.h2{font-size:1.25rem;line-height:1.5rem}}#challenge-error-text{background-image:url(data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIzMiIgaGVpZ2h0PSIzMiIgZmlsbD0ibm9uZSI+PHBhdGggZmlsbD0iI0IyMEYwMyIgZD0iTTE2IDNhMTMgMTMgMCAxIDAgMTMgMTNBMTMuMDE1IDEzLjAxNSAwIDAgMCAxNiAzbTAgMjRhMTEgMTEgMCAxIDEgMTEtMTEgMTEuMDEgMTEuMDEgMCAwIDEtMTEgMTEiLz48cGF0aCBmaWxsPSIjQjIwRjAzIiBkPSJNMTcuMDM4IDE4LjYxNUgxNC44N0wxNC41NjMgOS41aDIuNzgzem0tMS4wODQgMS40MjdxLjY2IDAgMS4wNTcuMzg4LjQwNy4zODkuNDA3Ljk5NCAwIC41OTYtLjQwNy45ODQtLjM5Ny4zOS0xLjA1Ny4zODktLjY1IDAtMS4wNTYtLjM4OS0uMzk4LS4zODktLjM5OC0uOTg0IDAtLjU5Ny4zOTgtLjk4NS40MDYtLjM5NyAxLjA1Ni0uMzk3Ii8+PC9zdmc+);background-repeat:no-repeat;background-size:contain;padding-left:34px}@media (prefers-color-scheme:dark){body{background-color:#222;color:#d9d9d9}}</style><meta http-equiv="refresh" content="390"></head><body class="no-js"><div class="main-wrapper" role="main"><div class="main-content"><noscript><div class="h2"><span id="challenge-error-text">Enable JavaScript and cookies to continue</span></div></noscript></div></div><script>(function(){window._cf_chl_opt={cvId: '3',cZone: "www.cardmarket.com",cType: 'managed',cRay: '8ede3cd9984850de',cH: 'f7Ah_y2qOkoLgxUd6LMENT_KufyejpYr8GEM47pfeKM-1733508678-1.2.1.1-nKNzMb_SjZ1lqdj6ROa_Xy1qqWOdm1vZqhBEDB2A_WcV89Ezoon7n3fAj9E8iyUJ',cUPMDTk: "\/?__cf_chl_tk=dqgjx3pd4QwP2zZzwYmE_7qrv0gIB5Uh_9qk__47yls-1733508678-1.0.1.1-eEx7MyKq8MUJVJnR15QTLFuasmZ9RAFdZf3seD5itHg",cFPWv: 'g',cITimeS: '1733508678',cTTimeMs: '1000',cMTimeMs: '390000',cTplC: 0,cTplV: 5,cTplB: 'cf',cK: "",fa: "\/?__cf_chl_f_tk=dqgjx3pd4QwP2zZzwYmE_7qrv0gIB5Uh_9qk__47yls-1733508678-1.0.1.1-eEx7MyKq8MUJVJnR15QTLFuasmZ9RAFdZf3seD5itHg",md: "mRarwpgTLEQ5F.10XrAVUjqv3NCQy0QeddZJuIJCyfs-1733508678-1.2.1.1-Ow.Af_V5hVIF9Im0lCg9b6oTaiYz8WTkalypuU0bB2jsYilMHmfCN4NelDUiWOH94XCraVZJyxEo4Z2wLKZu0b4Nmj8zylvN0BgJpYCvTK22rNcdFgoA99Jte4FgJP3D0jNJlUznI_B2h_g7eB0RJ5ROvH2Fl0k1QGlUELnpWnAVT40RBIsTRVnJ7QE1TYADJalEX8GrAuqrhndWlCUAS264o6WwGI32D6GR.flrPQkJTn_rl6EX62yK.0lscLuhQb5XSmUmWYYtZo3X2WpN7fuvYnMKZv0cDE_olgIDq9gVHaT.rBgVSq2FUBeKieNEorelq63Rulavzgb3V.QNGMBSNl_MC4uYlWeDtCaGI59SptswHjWspy49llJi2iKHBq6qSJOiCagCGPON1CcR0Jk3IpW3udW_8AkTL07yz9yrTl_7vA6m4e_g65Q2suPiK0t58sUqTU938XeMPpsXEIIlmC5a6b5Bu6bAotkcivHd3jjPKwnfI0_FaNFbCSNRPtL_WNaoINO0RDm7WRTuos0ww.E8MF2A2D6QlDTXVlkYwEY90Cans8cDcradQCCkiBmAdq4vYdFzz2sDHQThg8RFek0pgAAOccD0rAwlRwKR.dKV1_SVnmz.g2uy1cGD18xDv9sYPzR3SwTME8BmX.5.SvHOx3U1ht6UrfrZN93Cg74KfQNl7Uh7SbO6k_96QLMWiovT4lEcAv99WcXY3oVQ0_RbTKE2mMOwaUV7uFh5kjnABCPiI3njiNt11oWQzGug5Bi08K6QMnH9YuPSETWrFYvkT07pKHEahB2jJgS8307n0TRnCubyzZplhAOQ_hY3NTEevmjXQtsnPY01OUj0aauwCpmT73S7KwJBsq3R0lexbWJhNXmoaNeAKUv9auq22c1.BhB8r.nR4.pRO_kEBOlt6elEWIk7gKIA39aNy2z.bctogKBWCJNFYIgoAsk3c0HqQkcV3r2UaJFdXJF4NBV5317MZ4Zk1NoBWTSKCioae9DbFeq5Wsi2K2Ksx8pizXWNm.cU9B.GTPUKCFVfLxJunBkoanVcdi.JBhh3hd7zBPoyagwhR74L6gQvpTHmMkLENtRKBcW1bINtPRHqCpx2nI6fmWI7OUGjw5sPFiP9Jr3w6yoU3xTw7n9FUTvEH6rO6k92tHGl1AY15nHkzsmPgeN5o3xVbgfmwH.pwviYPN2ZVvx8tygjxr_hk6Og6lc2rllJ30aQ694DDkS2dGkaar5uH0ANCZZtOOAit11DSw52rhcIpGSY3xRZbQuNoRNJ3WwdF3P0x_OaeNnbHuCrB2ngekeuBPA9Ic3Cx2tQ2OmXuExyqNtdpUz1nuGOluKOXfjX31gF.BJkxA9vsuEu5qPH1ULzs1VQMnNQJpVHBbSeoTzgbrNNdX4PgREN3SdPJnK6ofg7t02pvWAiQ4nrlHrFZIGyufwTXGHMbWgeNKSt3Q5yhF2T31.rfywYrSAY1RKG4CMelI_ym0RwqYOkrnspH6PUYRiOBcysoYTeRe11M699V0G8a5sQxpY3hYq2fJG0JaVQAH.xm4Q75KpB4Y.6RkBEj6njrwhZo1OrH_0JXAgHS0uolHIkVzTdEPPHxDCEjcQFGENp1dA9ctsIJGs7Rj.TeFwpt6boxzG2JwZOEBdOmeEnI04hc2GvfMPTxsSKX0RnJ2q5Wy7M5i5zzMCGwyFDyrSEBar0AZYHnOa_V2XRJMG8SLKY3Md15EyLHmbbwpTqXHja7GGTjrh.5lhyxZPHEfMgy2tTDGYL91k0HAx6nTmS_pnePJhAuwg0uKLfiOPTDj03BAYCNFgFrWGuJF7JVSgqmDSglAj11c0evlBmBwtkizMiStZ8Sml9H80yMeakXa1LmnKg3_dk9Jl7JlTesgrkG0nsrPFOaUzy4NC_LB4dy7mAyWyd7BkfEOcOECp9lTriyLFTmWU3a9Ey5L3k_ZJcU0RVLPVFCKJeAsJf..NfzjzTwrkm29GcWwpN7BoIDDrGqIne.2LPKovCLKHc0PI8toPTSBc3qsIJa6YxNl8j_IM2z4HUexJYpPuoaHv1n7sKlR.GYLtM..Y2p_iPjWtd7rJmvvEBjyinCVotLkesSw9bZWC.rOAT72ZRSZyq7ih9SWOSNbGcaWLD6X1xhfoOxMjUdxAmXTRBQC8ZE6C8tjylvnDhxrCUoWtzTO4ADnjbUVEHkM.1iYZ82d0dFnjKDNyDE6ONKKqO_RWZGD9ZqxljBQH316X8pJYxeZPk2BXPbuMQNFc1OprGPj1B83Rc1ziHCkgUctzp9eBhp4MCoEbcDtmngm5dMFyVF1LJxZd8IL8.fTDvXh6VljOtkFU5I8Ob_sCxJ65AEbsUVLzud8Q6TO.tdnNdavfKTe8GdYHvwBhjHGQAaKSd6.RCqXaPuXt1TLHONJb4bZhbgpGkuugeK578Zc1OF6qLtbpUPoAfZ_S8wHek2dmPGLBwljLkKfg6sppChcwQiZaRuYXeV1roUehkFrHL58ZdSY4RTQ_ee.hs.crBhQB3ZMhnJonp0TnatWDn5Kf3EhUKiCNpZmU8bo8zRUop3S4sqygyirAu61l.M661DRk_.oy.K9uQmFLuaZ5_4fCnP468fFAwL.vtxL5EEWr58hnFiFyMNIhosQ",mdrd: "1mU15antGYzYdvEe9wIcSa3g.wsaP40FagrclXFS8a4-1733508678-1.2.1.1-8VIr80G5JDNMJ3Est7Pf43F7yN0DS7IUDLaZW5gNyH0xA0rvN6nlCbzt3aztiT6B5gePdgVxgLSRu3pQY9lo_DzkDD5EoNs7uu.sFkhJv5lud_fegeuhGear6if_ZKgpaRfSsVe.4Ams0RrQ97En0au7Dibo74qjovsZdPxi542fNl0DXiEWutORVAumRw.hI3YxeXFA1v5F5hZXNZQxcqMerufflhwWOz6zo4fkv.qAU2EdpNA4CPcWdI9CrC3jGk8oEkAhLIkpismK.l74bocy5nPr.djLbpzEiM0m7PrObjriZU.AIPToXZ7BtZYRTjPOG0ihK9NxD8MpXYmZx0oiqiipFgwrKoB91H3qNucxs0SnXmsqSNsZy9D2Hubi5y0S.EvLj78axvxs736D4EciHtoaeHe4XZ22OprddrLpGPBajaW9Di_lMiQi044tcvYEaonk2XU7fXb_AeuFcUKmsylahmPf6BxfRS073IHpG3FCLNS1irUBKn_37ngr6LTmY7q4TO3vedPaaId5GK8eNMwt35SWSeN8u0Lu6sm1UXKHRGCu910fEOzSoFAGZTDASyBaqpmJN0yCujGOjXRVXGCdK1tZE_yWZmeohRgKJZRg4QesCQaQXHxbLy7ASZtX5A09j9q.gBwy.NDfmw0msSOm.TW0bCEEV80ncdOZl28L5YXHZjk9wp4WairzKvkVFJMD9wyXEQRR5prNjoAJaaG0pDynfacHM2FhbEZkXnxi4V0sGyd9fZA_UHux_M05thxv7IxXLQKRLzsY4k0wxPJCl7rT.bbLoy4h1exlZu5HY332QyqnqWawwxqdo6OTTXTiz_kDvdExB0dxpMB3l.xrQgBUOzicg1PaALFRru9FpCyIYUOYpbMtu_xvbj0X8xKBGOLGwE5y7_7ayylGPrgA8oYHXWmxeuKgnjEuvU.QGqnz4VBP0qf0oEGT2W4N3K_N5L1c9TpgdQ2UsG6JPFUrUdE1o9V4N3uaitIP6r1s.AOcIB1TZ6EohjiNfI0K4c3o5aYC0K2C6hueV5MGuUQk4uf8pekfnJQt3Y5PvneshlJJRQFvcCMAAlRqKfbNo0._CbariyE5985NCwiNOoIxwxkykR6Z.XEdHKeCQXGV.yA4LJelLWRtyyM6HahT8eHoK2BMyYq7v9qkAkqHlWuerGzU0wxjqSWHsAHn2oVc2Hgfnd8BuT7xiK5_5ON9Yhg0PfNBeYX.0PyFP56ldvjxD.3lEr7uXU.CerlAjmiPf3yEtPpZ8r2WvRkKNCx05VzC.dlMZp2SsTm8jS1bIqelTMp3eLB3JLtwnHCrH0lbMgLG_Jtudvq4GfXitgo6JFif_SjaQCtROOAc_tkBo3VGB3ccqBqxWThY0Er5pcEEpefiBU2vVeWgVbMKxNY6dEeiLHfMp6WLOdeYgzdGtPJYWgfdCnRPvCq3dwkoWKohSeRSRjsLJHos2L_94_S1iBkI94jZnuUshm7KzRq6ZvYc_OPGm.FVg_1Sj_e2ly5bRKp0XwcBr.wPqQu8oGU7OkLOFZP7XgkBafjVH6Y6AeHAmyueIgFtbdjjYuFwtOo40_xNpBnUT.tAcHyn4sFTncFElIeGgSjHvN6b6a9US7nPTUamGOUpyekvFpWUPBNszWUGrFcgR73m6wwMAIOpjgjeL8PMPtBYhHVRmiSC8tCSIyRsJcs8FNu_5R7h3N5_0_BEEBpr11XsahNPuZWfIY2up7Ifzp3Gok_fuwaZeV7IGqZc3XqHSZUc0Tm.a4WUFnIRGVyTkjbndvW56bDlR4crjwhTO.PcIblM3QDIeCzQGashZW6Gw6npxco2Z0u53Xv615vZ6uem2B6eS7FqX5VLSHJp4CPvjBLPT9GC98GLdyQFvqtRY7KpR.VIOF0cCPYEElrCGi7Ze2lnFfh9EFJbAA_9cRiaF.vMRAOC_oJJQ5iuPSgqHA1HW4OSPuznvlXjjRt3hirZZV3sZYneEffMTPfwf4En1uiDoKonWSKCTyJcCaWofsa4seJcNBmflCffcyhMIT78bKaQ63abZ_k8E5LmiNRJsSky0i__baR.ukKvvofxGbMzg8aqddiHzZV2GdbmZqFe1spJl3r1sKKepYzhTdLDVyDI11OjKoBdTLJwbZVkCZuzWDNGFk5x1EZbk64o9bWI45_Pnc7.W07cEAD39xYBUGR7iYOwZUW7iIbyQv53NZTnbdXScuHh_mcKRmJT1htoJ6dvmjj9s.YgrMe4bG3mGBaDw5BH1h_BP7XL2gdSTrcpM4w"};var cpo = document.createElement('script');cpo.src = '/cdn-cgi/challenge-platform/h/g/orchestrate/chl_page/v1?ray=8ede3cd9984850de';window._cf_chl_opt.cOgUHash = location.hash === '' && location.href.indexOf('#') !== -1 ? '#' : location.hash;window._cf_chl_opt.cOgUQuery = location.search === '' && location.href.slice(0, location.href.length - window._cf_chl_opt.cOgUHash.length).indexOf('?') !== -1 ? '?' : location.search;if (window.history && window.history.replaceState) {var ogU = location.pathname + window._cf_chl_opt.cOgUQuery + window._cf_chl_opt.cOgUHash;history.replaceState(null, null, "\/?__cf_chl_rt_tk=dqgjx3pd4QwP2zZzwYmE_7qrv0gIB5Uh_9qk__47yls-1733508678-1.0.1.1-eEx7MyKq8MUJVJnR15QTLFuasmZ9RAFdZf3seD5itHg" + window._cf_chl_opt.cOgUHash);cpo.onload = function() {history.replaceState(null, null, ogU);}}document.getElementsByTagName('head')[0].appendChild(cpo);}());</script></body></html>
Failed to fetch the page. Status code: 403

In [ ]:

# Parse the content (update selectors based on the structure)
cards = soup.find_all("div", class_="row no-gutters")  # Example class for card rows (inspect the actual site)

for card in cards:
    try:
        name = card.find("a", class_="product-name").text.strip()
        price = card.find("span", class_="price").text.strip()
        print(f"Card Name: {name}, Price: {price}")
    except AttributeError:
        # Skip rows that don't match the expected structure
        continue